{
    "Target": {
        "EntitySet": "ClientRegistrationSet",
        "Service": "/EpmCacheApp/Services/MbtEpmDemo.service",
        "ReadLink": "{@odata.readLink}"
    },
    "OnSuccess": "/EpmCacheApp/Actions/DeleteEntitySuccessMessage.action",
    "OnFailure": "/EpmCacheApp/Actions/DeleteEntityFailureMessage.action",
    "ActionResult": {
        "_Name": "delete"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}