{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "BusinessPartnerSet",
        "Service": "/EpmCacheApp/Services/MbtEpmDemo.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "AddressType": "#Control:AddressType/#Value",
        "Building": "#Control:Building/#Value",
        "City": "#Control:City/#Value",
        "Country": "#Control:Country/#Value",
        "PostalCode": "#Control:PostalCode/#Value",
        "Street": "#Control:Street/#Value",
        "BusinessPartnerID": "#Control:BusinessPartnerID/#Value",
        "BusinessPartnerRole": "#Control:BusinessPartnerRole/#Value",
        "CompanyName": "#Control:CompanyName/#Value",
        "FaxNumber": "#Control:FaxNumber/#Value",
        "LegalForm": "#Control:LegalForm/#Value",
        "PhoneNumber": "#Control:PhoneNumber/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/EpmCacheApp/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/EpmCacheApp/Actions/UpdateEntityFailureMessage.action"
}