{
	"_Type": "Action.Type.ODataService.Initialize",
	"ActionResult": {
		"_Name": "init"
	},
	"OnFailure": "/EpmCacheApp/Actions/MbtEpmDemo/Service/InitializeOfflineFailureMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Downloading...",
	"Service": "/EpmCacheApp/Services/MbtEpmDemoOnline.service"
}